Fixed strange bug causing the following macro structure to throw [Macro error in gettext: TypeError: Cannot find function replace in object Public. (/opt/helma/apps/antville/code/Global/i18n.js#100)]: <% gettext <% item.status | capitalize %> %>